name: Drone Agent node(s) 
description: >-
  Drone Agents
version: 0.8.2-rancher1
minimum_rancher_version: v1.1.1
category: Continuous Integration
maintainer: Engineering <engineering@rancher.com>
license: Apache 2
projectURL: https://github.com/rancher/rancher-tools-catalog
